# Generated by Django 2.2.14 on 2020-07-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='skills',
        ),
    ]
